### ISSUE TITLE
Minimization

### ISSUE THREAD

**Issue by realill** [steveash/jopenfst#1]
Hello @steveash .

I see that you have removed minimization from readme file here 
https://github.com/steveash/jopenfst/commit/6b6a9b36b8956dbec4b9c5e4338527984e71327b

What happens with it?

I kind of need fst minimization right now. But I need a version of minimization that does not rearrange weights and ilabel/olabel combination inside arcs. Kaldi have similar patches for fstminimize, at least they seem to prevent ilabel/olabel rearranging.

Also I do have implementation for OpenFstReader/OpenFstWriter, that allow to read/write openfst file formats. They are not perfect but still work well with default openfst models. I can contribute this code here.

**Comment by steveash** [comment]
Hi. The reason that I removed minimization from the readme is that it was actually never implemented. The original code from John only had a few of the typical algorithms and unfortunately didn't include minimization. I do plan on adding it, but if I'm being honest it will probably be the mid-spring before I can spend time on it. A pull request would certainly be welcome.

I mentioned this in the readme as well, but I do want to warn you that the code is still very beta. John's original code was never really used by another project and while the unit tests passed -- there were a number of issues that I've since had to correct.  I am using this in my jG2P project so I have some confidence -- but there are a number of features and api cleanup/refactoring that I'm still doing from John's original code as I use it more in more in my jg2p project. But after I am finished with jg2p and my synthrec project that I'm currently doing, and am confident and comfortable with the stability of the API, I will GA a 1.0 version of this.

For the OpenFstReader/writer -- is this to parse the arpa formats or their binary serialized formats? I have a arpa reader/writer already in this code base (though I would welcome improvements).  If you have reader/writer that can speak openfsts binary format I would *love* that.  I could use those to build some better unit tests to ensure that my port code is behaving similarly to their code, which has certainly had many more eyes looking at it than mine.

Thanks!

**Comment by realill** [comment]
Yes, it is for binary format. Openfst binary format is a bit complicated, but I do read/write "default" stuff that other fstsomething commands generate/read. I use it to run fstminizmize.

This code is owned by company I work for api.ai. I will check with our CTO about it again, and probably share the code under MIT.

**Comment by realill** [comment]
I can not share reader/writer code right now, maybe later.

Closing this.
