### ISSUE TITLE
Writing cyclic FST to binary file

### ISSUE THREAD

**Issue by jolly-tao** [steveash/jopenfst#2]
Hi @steveash ,

I am trying to use jopenfst as an FST based decoder. In my situation, there are some FST models generated from openfst command line tools in text format. Decoding is expected to be done on Java side, so I think jopenfst is a good choice.

However, when looking at `Convert.importFst()`, I found it assumes that the model is read as resources. The models I use are larger than 600MB, so I would prefer to load them by specifying file names.

Fortunately, there is `FstInputOutput.readFstFromBinaryFile()` requiring a File object. Before calling it I should convert the text model files into Java binary files. So I turned to the command line utility class `Import` under the `io` package. It seems that if the model has self loops, the serialization leads to StackOverflowError. Taking a glance at the stack trace, I guess the reason may be that [`stateMap.put()`](https://github.com/steveash/jopenfst/blob/master/src/main/java/com/github/steveash/jopenfst/FstInputOutput.java#L204) triggered `MutableState.hashCode()` which in turn triggered `MutableArc.hashCode()`. Since the FST has loop arcs, the state->arc->state->arc sequence keeps going on.

A simple cyclic model reproducing this problem would be:
```
cyclic.fst.txt
========================================
0	1	a	x	0.5
1	1	b	y	1.5
1	2	c	z	2.5
2	3.5

cyclic.input.syms
========================================
a	0
b	1
c	2

cyclic.output.syms
========================================
x	0
y	1
z	2
```

Anyway, I saw `MutableFst.saveModel()` is annotated as deprecated.

So my questions are:
1. Is there a better way loading FST model as a file instead of resource?
2. If java binary file is the only choice, will writing cyclic model be supported?

Correct me if I am wrong or missing something.

**Comment by steveash** [comment]
Hi @jolly-tao -

1. I think loading by File instead of only via classpath resource makes sense. Convert.importFst is the right entry point. I have added new File based overloads.
2. Models with cycles are/will certainly always be supported. I fixed the bug in hashcode and that hashmap (with the put triggering the hashcode) should've been an identityHashMap anyways. Thats fixed too. 
3. If you are building the models (and minimizing, determinizing, etc.) in OpenFST and then you want to run them in production in java using jopenfst -- then exporting the text and running that through Convert.importFst is good. The MutableFst that you get from Convert can be saved with save() I removed that Deprecated annotation.  The serialized models are much more compact so for delivering in production that should be fine. Originally i added the deprecation to encourage just storing the text since that was always going to be compatible but I've got version numbers in the binary stream so I'll try to keep things backwards compatible (I need to for my stuff anyways)
4. At runtime -- its important to note that MutableFst instances are not thread safe and not particularly optimized for performance. If your problem supports it, I would load the binary serialized and then convert it to an ImmutableFst like:
```java
new ImmutableFst(FstInputOutput.readFstFromBinaryFile(file))
```
the immutable fst is faster and threadsafe.

I hope that solves all of your problems. If you can use the current code (with my last few commits fixing these problems that you found), let me know if it all works for you.  I can release a new version 0.1.1.ALPHA to maven central once you confirm its all good. 

Also please feel free to suggest any other changes. I have some more free time now so I plan to clean this up, add more doc, add some of the missing important FST operations (minimization), and maybe get close to releasing a 1.0 version.  So any suggestions or pain points are very welcome.

**Comment by jolly-tao** [comment]
Awesome. Thanks very much for your quick reply and fixes.
Both loading by `File` and serialization of cyclic models work perfectly now.

What I am doing is:
1. Load the pre-compiled model from OpenFst as a `MutableFst`.
2. Construct a MutableFst which maps the input sequence to itself.
3. Compose the above two and apply `NShortestPaths` on the composed fst.

> its important to note that MutableFst instances are not thread safe and not particularly optimized for performance.

The fst returned by `Compose.compose` contains the expected I want, but your reminder concerns a little bit.

> the immutable fst is faster and threadsafe.

Yes, loading the model as an `ImmutableFst` followed by calling `Compose.composeSimple` is very fast, except that the fst returned has only two states without a final state in my case. Sorry that I cannot repreduce it with a simpe input example. But I guess that epsilon transitions in the model causes this problem. Maybe I should use `fstrmepsilon` during model generation in order to use `ImmutableFst` and `Compose.composeSimple`?

**Comment by steveash** [comment]
I'm not sure that I follow exactly what you're trying to do: are you loading this big model (described by fstinfo) and then composing it with much smaller fsts many times by many threads? (i.e. one big model and a bunch of user requests querying that model via compose?)  If that is your use case, then yes making the big model an ImmutableFst would be a good idea.  If you aren't doing multiple requests by multiple threads then the thread safety isn't an issue. MutableFsts are fine to use thread confined -- i.e. there are no static fields that cause problems.

composeSimple with epsilons could be a problem - yes. I'll look at that later tonight.

**Comment by jolly-tao** [comment]
> are you loading this big model (described by fstinfo) and then composing it with much smaller fsts many times by many threads?

Exactly. I'll just use `compose` and surround it with `synchronized` for the moment.

> composeSimple with epsilons could be a problem - yes. I'll look at that later tonight.
Good to hear that.

Anyway, serialization is working well. Please release the new version.
I'm closing this issue.

**Comment by steveash** [comment]
0.1.1.ALPHA is released on maven central. It might take a few mins to sync
